apiVersion: kueue.x-k8s.io/v1beta2
kind: AdmissionCheck
metadata:
  labels:
    test-cluster: manager
  name: mk-ac
spec:
  controllerName: kueue.x-k8s.io/multikueue
  parameters:
    apiGroup: kueue.x-k8s.io
    kind: MultiKueueConfig
    name: multikueue-config-2
